#!/usr/bin/env python3
"""Assemble the whole MAI migration as one file, in the order it must run.

    python make_migration.py <dbmai-dir> <dbmai_eventai-dir> <output.sql>

WHY A SCRIPT AND NOT A DIRECTORY OF FILES

The converters write one file per script and one per creature -- 688 and 5,822
of them -- because that is the shape a person edits: you open the creature you
are working on. It is not the shape a migration runs in. A migration has an
order, and three parts of this one genuinely depend on the two before them:

    1. the schema, and the text merge, which must happen before anything
       references a text id
    2. the rows
    3. `creature_template.AIName`, which must be last -- the moment a creature
       says MAI, the server expects its rules to be there

So the pieces stay as they are and this puts them in order, once, into
something that can be run and rolled back as a unit.

WHAT IS NOT HERE, AND WHY

`creature_ai_summons` has no MAI table and needs none. Its 28 rows held a
position and a despawn time, looked up at run time by a spawn id -- and the
conversion resolves that lookup: every summon step carries its own x/y/z/o and
its own despawn_delay, which is exactly what the `at` facet is for. Porting the
table would be porting an indirection that no longer has a reader.

The old tables are dropped at the end rather than in the middle, and only after
everything that read them is gone.
"""
import io
import os
import sys

EOL = chr(10)

HEADER = """-- MAI: the whole migration, in the order it must run.
--
-- Generated by tools/make_migration.py from the converters' output. Do not
-- edit here; edit the rows the converters read, convert again, and reassemble.
--
-- IDEMPOTENT, and by rebuilding rather than by merging: schema.sql drops and
-- recreates every MAI table, so a second run starts from empty ones and lands
-- in exactly the same place. That is the honest form for a conversion -- the
-- source of truth is still `creature_ai_scripts` and `db_scripts` until they
-- are dropped, and MAI's tables are derived from them.
--
-- NOT wrapped in a transaction, and deliberately not. MySQL commits implicitly
-- at every CREATE and DROP, so a START TRANSACTION around this file would
-- cover nothing while implying it covered everything. The one statement that
-- would benefit is the final UPDATE, and a single statement is atomic already.
--
-- NEEDS THE `mysql` CLIENT. The text merge is a stored procedure and uses
-- DELIMITER, which is a client directive rather than SQL -- most GUI tools and
-- driver-level executors do not understand it.
--
-- ORDER MATTERS, and in three places it is not obvious:
--
--   * the text merge comes first, because every `talk` in the rows below names
--     a text id and the merge is what makes those ids resolvable from one
--     table
--   * `AIName` comes LAST. The moment a creature_template says MAI, the server
--     expects that creature's rules to exist; setting it before the rows are
--     in gives a window where a pull produces a creature that does nothing
--   * the old tables are dropped after all of it, and only because nothing
--     reads them any more -- EventAI was removed in the same change
--
-- `creature_ai_summons` is deliberately absent. Its 28 rows were a position
-- and a despawn time behind a spawn id, and the conversion resolved that
-- lookup into the steps themselves: every summon carries its own x/y/z/o now.
-- There is no table to port because there is nothing left to look up.

"""

FOOTER = """
-- ---------------------------------------------------------------------------
-- LAST: the creatures start using it.
--
-- 5,822 rows, and the only irreversible-looking part of the migration -- which
-- is why the old value is kept rather than overwritten blind. `AIName` was
-- 'EventAI' on exactly these creatures; if the rules turn out wrong, the way
-- back is one UPDATE and a restart.

UPDATE `creature_template` SET `AIName` = 'MAI' WHERE `AIName` = 'EventAI';

-- ---------------------------------------------------------------------------
-- AFTERWARDS, and NOT in the transaction above: the tables nothing reads.
--
-- Left commented on purpose. Dropping them is a decision about a backup, not a
-- step of the migration, and a migration that silently destroys the thing it
-- converted from is one nobody can check afterwards. Run these when the
-- conversion has been live long enough to trust.
--
--   DROP TABLE `creature_ai_scripts`;
--   DROP TABLE `creature_ai_summons`;
--   DROP TABLE `creature_ai_texts`;
--   DROP TABLE `script_texts`;
--   DROP TABLE `db_script_string`;
"""


def gather(directory, banner):
    """Every .sql in @a directory, in name order, under one banner."""
    if not os.path.isdir(directory):
        sys.stderr.write('error: %s is not a directory\n' % directory)
        return None, 0

    names = sorted(n for n in os.listdir(directory) if n.endswith('.sql'))

    out = [
        '-- ' + '-' * 73,
        '-- ' + banner,
        '-- ' + '%d file(s), assembled in name order.' % len(names),
        '',
    ]

    for name in names:
        # 000_migrate_to_mai.sql is the schema and is emitted separately, in
        # front of everything: it creates the tables the rest insert into.
        if name.startswith('000_'):
            continue
        out.append(io.open(os.path.join(directory, name),
                           encoding='utf-8').read().rstrip())
        out.append('')

    return EOL.join(out), len(names)


def main():
    if len(sys.argv) != 4:
        sys.stderr.write(__doc__)
        return 1

    scripts, rules, target = sys.argv[1], sys.argv[2], sys.argv[3]

    # The output must not land in either input directory. It ends in .sql, so
    # the next run would read its own previous output and double everything --
    # quietly, because a doubled INSERT of the same primary key is a duplicate
    # key error a thousand lines in, not at the top.
    where = os.path.dirname(os.path.abspath(target))
    for source in (scripts, rules):
        if os.path.abspath(source) == where:
            sys.stderr.write('error: %s would be read back in on the next '
                             'run; write it outside %s\n' % (target, source))
            return 1

    here = os.path.dirname(os.path.abspath(__file__))
    schema = os.path.join(os.path.dirname(here), 'schema.sql')

    parts = [HEADER]

    parts.append('-- ' + '-' * 73)
    parts.append('-- THE SCHEMA, and the text merge inside it.')
    parts.append('')
    parts.append(io.open(schema, encoding='utf-8').read().rstrip())
    parts.append('')

    sequences, count_sequences = gather(scripts, 'THE SEQUENCES, from db_scripts.')
    if sequences is None:
        return 1
    parts.append(sequences)

    ruleset, count_rules = gather(rules, 'THE RULES, from creature_ai_scripts.')
    if ruleset is None:
        return 1
    parts.append(ruleset)

    parts.append(FOOTER)

    io.open(target, 'w', encoding='utf-8', newline=EOL).write(EOL.join(parts))

    size = os.path.getsize(target)
    print('%s: %d sequence file(s), %d rule file(s), %.1f MiB'
          % (target, count_sequences, count_rules, size / (1024.0 * 1024.0)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
